/*
 * File: app/view/admin/allergies/Allergies.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PatientChart.view.admin.allergies.Allergies', {
    extend: 'Ext.window.Window',
    alias: 'widget.allergies',

    requires: [
        'PatientChart.view.admin.allergies.AllergiesViewModel',
        'PatientChart.view.admin.allergies.AllergiesViewController',
        'Ext.panel.Tool',
        'Ext.grid.Panel',
        'Ext.grid.column.Column',
        'Ext.form.field.Text',
        'Ext.grid.View',
        'Ext.grid.plugin.RowEditing',
        'Ext.selection.RowModel',
        'Ext.toolbar.Toolbar',
        'Ext.toolbar.TextItem'
    ],

    controller: 'adminallergiesallergies',
    viewModel: {
        type: 'adminallergiesallergies'
    },
    constrain: true,
    height: 250,
    width: 400,
    layout: 'fit',
    title: 'Edit Allergy Types',

    tools: [
        {
            xtype: 'tool',
            type: 'plus',
            listeners: {
                click: 'onAddRecord'
            }
        },
        {
            xtype: 'tool',
            type: 'minus',
            bind: {
                disabled: '{!selectedRecord}'
            },
            listeners: {
                click: 'onDeleteRecords'
            }
        },
        {
            xtype: 'tool',
            type: 'refresh',
            listeners: {
                click: 'onRefreshClick'
            }
        }
    ],
    items: [
        {
            xtype: 'gridpanel',
            reference: 'grid',
            header: false,
            title: 'My Grid Panel',
            store: 'Allergies',
            bind: {
                selection: '{selectedRecord}'
            },
            columns: [
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'text',
                    text: 'Label',
                    flex: 1,
                    editor: {
                        xtype: 'textfield',
                        allowBlank: false,
                        allowOnlyWhitespace: false,
                        emptyText: 'New Allergy'
                    }
                }
            ],
            plugins: [
                {
                    ptype: 'rowediting',
                    listeners: {
                        edit: 'onRowEditingEdit',
                        canceledit: 'onRowEditingCanceledit'
                    }
                }
            ],
            selModel: {
                selType: 'rowmodel',
                allowDeselect: true,
                mode: 'MULTI'
            }
        }
    ],
    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'bottom',
            height: 30,
            items: [
                {
                    xtype: 'tbtext',
                    flex: 1,
                    reference: 'lastupdated',
                    bind: {
                        text: 'Updated: {grid.selection.updatedate:date(\'m/d/Y H:i a\')} by {grid.selection.updateuser}'
                    }
                }
            ]
        }
    ]

});