/*
 * File: app/model/AnatomyDiagram.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PatientChart.model.AnatomyDiagram', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.Integer',
        'Ext.data.proxy.Ajax'
    ],

    fields: [
        {
            name: 'name'
        },
        {
            name: 'type'
        },
        {
            name: 'spriteClass'
        },
        {
            type: 'int',
            name: 'segmentWidth'
        },
        {
            type: 'int',
            name: 'segmentHeight'
        },
        {
            type: 'int',
            name: 'segments'
        },
        {
            type: 'int',
            name: 'imagesPerClass'
        }
    ],

    proxy: {
        type: 'ajax',
        url: 'resources/data/anatomy.json'
    }
});