/*
 * File: app/model/BillingCode.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PatientChart.model.BillingCode', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.Integer',
        'Ext.data.field.String',
        'Ext.data.field.Number',
        'Ext.data.field.Date',
        'Ext.data.proxy.Rest',
        'Ext.data.reader.Json'
    ],

    fields: [
        {
            type: 'int',
            name: 'id'
        },
        {
            name: 'code'
        },
        {
            name: 'text'
        },
        {
            type: 'string',
            defaultValue: '',
            name: 'description'
        },
        {
            type: 'float',
            defaultValue: 0.00,
            name: 'fee'
        },
        {
            name: 'updateuser'
        },
        {
            type: 'date',
            name: 'updatedate'
        },
        {
            type: 'date',
            name: 'begintime'
        }
    ],

    proxy: {
        type: 'rest',
        url: 'http://webapps.figleaf.com/rest/prototypes/billingcode',
        format: 'json',
        withCredentials: true,
        reader: {
            type: 'json',
            rootProperty: 'records'
        }
    }
});