/*
 * File: app/model/HospitalStat.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PatientChart.model.HospitalStat', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.Number',
        'Ext.data.field.Integer',
        'Ext.data.proxy.JsonP'
    ],

    fields: [
        {
            name: 'id'
        },
        {
            type: 'float',
            name: 'averagecoveredcharges'
        },
        {
            type: 'float',
            name: 'averagemedicarepayments'
        },
        {
            type: 'float',
            name: 'averagetotalpayments'
        },
        {
            name: 'drgcode'
        },
        {
            name: 'city'
        },
        {
            name: 'providerstate'
        },
        {
            name: 'providername'
        },
        {
            type: 'int',
            name: 'totaldischarges'
        }
    ],

    proxy: {
        type: 'jsonp',
        url: 'http://webapps.figleaf.com/webservices/hospitalresearch.cfc?method=search'
    }
});