/*
 * File: app/model/Patient.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PatientChart.model.Patient', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.Date',
        'Ext.data.proxy.Rest',
        'Ext.data.reader.Json'
    ],

    fields: [
        {
            name: 'id',
            type: 'int'
        },
        {
            name: 'firstname',
            validations: [
                {
                    type: 'presence'
                }
            ]
        },
        {
            name: 'lastname',
            validations: [
                {
                    type: 'presence'
                }
            ]
        },
        {
            type: 'date',
            name: 'dob',
            dateFormat: 'F, j Y H:i:s'
        },
        {
            name: 'gender',
            validations: [
                {
                    type: 'inclusion',
                    list: [
                        'Male',
                        'Female'
                    ]
                }
            ]
        },
        {
            name: 'email',
            validations: [
                {
                    type: 'email'
                }
            ]
        },
        {
            name: 'address'
        },
        {
            name: 'city'
        },
        {
            name: 'state'
        },
        {
            name: 'zip'
        },
        {
            name: 'photoUrl'
        },
        {
            name: 'allergies'
        },
        {
            name: 'preexistingconditions'
        },
        {
            name: 'notes'
        }
    ],

    proxy: {
        type: 'rest',
        url: 'http://webapps.figleaf.com/rest/prototypes/patient',
        withCredentials: true,
        format: 'json'
    }
});