/*
 * File: app/view/research/hospitals/InPatientPaymentsViewController.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PatientChart.view.research.hospitals.InPatientPaymentsViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.researchhospitalsinpatientpayments',

    providerGroupRenderer: function(groupVal,groupVals,fieldname) {
        return Ext.util.Format.plural(groupVal, " Provider");
    },

    onTreepanelCheckChange: function(node, checked, eOpts) {
        var nodes = Ext.Array.merge(
        this.lookupReference('statefiltertree').getChecked(),
        this.lookupReference('procedurefiltertree').getChecked()
        );

        var nodeValue=null, nodeType=null, nodeModifier = null, serverFilters = [];
        var filters = {};

        for (var i=0; i<nodes.length; i++) {
            nodeValue = nodes[i].get('id').split(':');
            nodeType = nodeValue[0];
            nodeModifier = nodeValue[1];
            if (!filters[nodeType]) {
                filters[nodeType] = [];
            }
            filters[nodeType].push(nodeModifier);
        }


        for (var i in filters) {
            serverFilters.push({
                property: i,
                value: filters[i]
            });
        }

        var store = this.getStore('HospitalStats');
        store.clearFilter(true);
        store.filter(serverFilters);
    },

    onProcedureFilterCheckChange: function(node, checked, eOpts) {
        this.onTreepanelCheckChange();
    },

    onHelpClick: function(tool, e, owner, eOpts) {
        Ext.Msg.alert("About the dataset",
        "The data provided here include hospital-specific charges for the more than 3,000 U.S. hospitals that receive Medicare Inpatient Prospective Payment System (IPPS) payments for the top 100 most frequently billed discharges, paid under Medicare based on a rate per discharge using the Medicare Severity Diagnosis Related Group (MS-DRG) for Fiscal Year (FY) 2011. These DRGs represent more than 7 million discharges or 60 percent of total Medicare IPPS discharges.");
    },

    onDownload: function(tool, e, owner, eOpts) {
        this.lookupReference('datagrid').downloadExcelXml();
    }

});
