/*
 * File: app/view/research/hospitals/InPatientPaymentsViewModel.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PatientChart.view.research.hospitals.InPatientPaymentsViewModel', {
    extend: 'Ext.app.ViewModel',
    alias: 'viewmodel.researchhospitalsinpatientpayments',

    requires: [
        'Ext.data.TreeStore',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json',
        'Ext.data.field.Field'
    ],

    data: {
        filterSelection: null
    },

    stores: {
        StateFilters: {
            type: 'tree',
            autoLoad: false,
            root: {
                expanded: true
            },
            proxy: {
                type: 'ajax',
                url: 'http://webapps.figleaf.com/webservices/hospitalresearch.cfc?method=getStateFilters',
                reader: {
                    type: 'json'
                }
            },
            fields: [
                {
                    name: 'text'
                }
            ]
        },
        ProcedureFilters: {
            type: 'tree',
            root: {
                expanded: true
            },
            proxy: {
                type: 'ajax',
                url: 'http://webapps.figleaf.com/webservices/hospitalresearch.cfc?method=getProcedureFilters',
                reader: {
                    type: 'json'
                }
            }
        },
        HospitalStats: {
            groupField: 'drgcode',
            pageSize: 500,
            remoteFilter: true,
            model: 'PatientChart.model.HospitalStat'
        }
    }

});