/*
 * File: app/view/patientchart/Anatomy.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PatientChart.view.patientchart.Anatomy', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.patientchartanatomy',

    requires: [
        'PatientChart.view.patientchart.AnatomyViewModel',
        'PatientChart.view.patientchart.AnatomyViewController',
        'Ext.toolbar.Toolbar',
        'Ext.form.field.ComboBox',
        'Ext.slider.Single'
    ],

    controller: 'patientchartanatomy',
    viewModel: {
        type: 'patientchartanatomy'
    },
    reference: 'anatomyviewer',
    width: 235,
    title: 'Anatomy',

    bind: {
        bodyStyle: '{cssStyle}'
    },
    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'top',
            height: 40,
            items: [
                {
                    xtype: 'combobox',
                    flex: 1,
                    fieldLabel: '',
                    labelWidth: 45,
                    emptyText: 'Please Select',
                    displayField: 'name',
                    forceSelection: true,
                    queryMode: 'local',
                    valueField: 'name',
                    bind: {
                        store: '{AnatomyDiagrams}',
                        selection: '{diagram}'
                    },
                    listeners: {
                        change: 'onDiagramChange',
                        afterrender: 'onDiagramComboAfterRender'
                    }
                }
            ]
        },
        {
            xtype: 'toolbar',
            dock: 'bottom',
            ui: 'basecolorbackground',
            height:30,
            items: [
                {
                    xtype: 'slider',
                    flex: 1,
                    reference: 'spriteSelector',
                    width: 400,
                    fieldLabel: 'Label',
                    hideLabel: true,
                    useTips: false,
                    publishOnComplete: false,
                    bind: {
                        disabled: '{!diagram}',
                        value: '{spriteSegment}'
                    },
                    listeners: {
                        drag: 'onSliderDrag'
                    }
                }
            ]
        }
    ],
    listeners: {
        afterrender: 'onPanelAfterRender'
    }

});