/*
 * File: app/view/patientchart/AnatomyViewModel.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PatientChart.view.patientchart.AnatomyViewModel', {
    extend: 'Ext.app.ViewModel',
    alias: 'viewmodel.patientchartanatomy',

    requires: [
        'Ext.data.Store',
        'Ext.app.bind.Formula'
    ],

    data: {
        diagram: null,
        spriteSegment: 0
    },

    stores: {
        AnatomyDiagrams: {
            autoLoad: true,
            model: 'PatientChart.model.AnatomyDiagram'
        }
    },
    formulas: {
        cssStyle: {
            get: function(data) {
                if (data.diagram) {
                    var imagesPerFile = data.diagram.get('imagesPerClass');
                    var pos = -1 * (data.spriteSegment % imagesPerFile) * data.diagram.get('segmentWidth');

                    var style = {
                        'background-position' : pos + 'px',
                        'background-repeat': 'no-repeat',
                        'background-color' : '#ffffff'
                    };

                    console.log(style);
                    return style;
                }

            },
            bind: {
                spriteSegment: '{spriteSegment}',
                diagram: '{diagram}'
            }
        }
    }

});