/*
 * File: app/view/patientchart/AnatomyViewController.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PatientChart.view.patientchart.AnatomyViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.patientchartanatomy',

    config: {
        currentSpriteCls: ''
    },

    setSpriteCls: function() {
        var vm = this.getView().getViewModel();
        var diagram = vm.get('diagram');
        if (diagram) {

          var selector = this.lookupReference('spriteSelector'),
                         segments = diagram.get('segments');

          var spriteNum = Math.ceil((vm.get('spriteSegment') + 1)/diagram.get('imagesPerClass'));

          var spriteClass =diagram.get('spriteClass') + spriteNum;

          if (spriteClass != this.currentSpriteCls) {
                this.getView().removeBodyCls(this.currentSpriteCls);
                this.getView().addBodyCls(spriteClass);
                this.currentSpriteCls = spriteClass;
           }
        }

        if (diagram != this.dataDiagram) {
            selector.setMaxValue(segments - 1);
            selector.setValue(0);
            this.dataDiagram = diagram;
            this.setSpriteCls();
        }
    },

    initViewModel: function(vm) {


        /*
        vm.bind(
            {
                spriteSegment: '{spriteSegment}',
                diagram: '{diagram}'
            },
            this.setSpriteCls,
            this
        );
        */
    },

    onBodyMouseOver: function(event) {
        console.log(event);

    },

    onBodyMouseDown: function() {
        this.getView().body.on('mousemove', this.onBodyMouseOver, this);
    },

    onBodyMouseUp: function() {
        this.getView().body.un('mousemove',this.onBodyMouseOver,this);
    },

    onDiagramChange: function(field, newValue, oldValue, eOpts) {
        this.setSpriteCls();
    },

    onDiagramComboAfterRender: function(component, eOpts) {

        var s = component.getStore();
        if (s) {
            if (s.getCount() == 0) {
                Ext.defer(this.onDiagramComboAfterRender,200,this,[component,eOpts]);
            } else {
                component.select(s.getAt(0));
                this.setSpriteCls();
            }
        }
    },

    onSliderDrag: function(slider, e, eOpts) {
        this.setSpriteCls();
    },

    onPanelAfterRender: function(component, eOpts) {
        component.body.on('mousedown', this.onBodyMouseDown,this);
        component.body.on('mouseup', this.onBodyMouseUp,this);
        // component.body.on('mouseover', this.onBodyMouseOver, this);
    }

});
