/*
 * File: app/view/patientchart/PatientChart.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PatientChart.view.patientchart.Main', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.patientchartPerspective',

    requires: [
        'PatientChart.view.patientchart.MainViewModel',
        'PatientChart.view.patientchart.MainViewController',
        'PatientChart.view.patientchart.graphs.Graphs',
        'PatientChart.view.patientchart.Anatomy',
        'PatientChart.view.patientchart.media.Media',
        'PatientChart.view.patientchart.procedures.Procedures',
        'Ext.tab.Panel',
        'Ext.form.Panel',
        'Ext.tab.Tab',
        'Ext.Img',
        'Ext.form.field.Date',
        'Ext.form.RadioGroup',
        'Ext.form.field.Radio',
        'Ext.form.field.File',
        'Ext.form.field.Tag',
        'Ext.form.FieldSet',
        'Ext.panel.Tool',
        'Ext.grid.Panel',
        'Ext.grid.column.Date',
        'Ext.grid.column.Number',
        'Ext.grid.View',
        'Ext.XTemplate',
        'Ext.ux.form.TinyMCETextArea',
        'Ext.grid.plugin.RowEditing'
    ],

    controller: 'patientchartmainviewcontroller',
    viewModel: {
        type: 'patientchartmainviewmodel'
    },
    reference: 'patientchart',
    layout: 'border',
    header: false,
    title: 'Patient Chart',

    items: [{
        xtype: 'tabpanel',
        deferredRender: false,
        plain: true,
        flex: 1,
        region: 'center',
        removePanelHeader: false,
        tabPosition: 'bottom',
        listeners: {
            tabchange: 'onPatientChartTabChange'
        },
        items: [{
            xtype: 'form',
            reference: 'patientform',
            autoScroll: true,
            layout: 'auto',
            bodyPadding: 5,
            title: 'Patient Information',
            items: [{
                xtype: 'container',
                layout: {
                    type: 'hbox',
                    align: 'stretch'
                },
                items: [{
                    xtype: 'component',
                    border: 1,
                    height: 164,
                    bind: {
                        style: {
                            border: '1px solid black',
                            'border-radius': '5px',
                            'background-image': 'url({profileImage})',
                            'background-repeat': 'no-repeat',
                            'background-size': 'cover'
                        }
                    },
                    width: 173
                }, {
                    xtype: 'container',
                    flex: 1,
                    margin: '0 5 0 5',
                    defaults: {
                        anchor: '100%'
                    },
                    layout: 'anchor',
                    items: [{
                        xtype: 'textfield',
                        fieldLabel: 'First Name',
                        name: 'firstname',
                        allowBlank: false
                    }, {
                        xtype: 'textfield',
                        fieldLabel: 'Last Name',
                        name: 'lastname',
                        allowBlank: false
                    }, {
                        xtype: 'textfield',
                        fieldLabel: 'Address',
                        name: 'address'
                    }, {
                        xtype: 'fieldcontainer',
                        layout: 'hbox',
                        fieldLabel: 'City,State,Z',
                        items: [{
                            xtype: 'textfield',
                            flex: 1,
                            margin: '0 5 0 0',
                            fieldLabel: '',
                            name: 'city'
                        }, {
                            xtype: 'combobox',
                            margin: '0 5 0 0',
                            width: 80,
                            hideLabel: true,
                            name: 'state',
                            displayField: 'abbreviation',
                            forceSelection: true,
                            queryMode: 'local',
                            store: 'States',
                            valueField: 'abbreviation'
                        }, {
                            xtype: 'textfield',
                            width: 100,
                            hideLabel: true,
                            name: 'zipcode'
                        }]
                    }, {
                        xtype: 'textfield',
                        fieldLabel: 'Email',
                        name: 'email',
                        vtype: 'email'
                    }, {
                        xtype: 'datefield',
                        fieldLabel: 'Date of Birth',
                        name: 'dob'
                    }, {
                        xtype: 'radiogroup',
                        fieldLabel: 'Gender',
                        allowBlank: false,
                        layout: 'hbox',
                        items: [{
                            xtype: 'radiofield',
                            name: 'gender',
                            boxLabel: 'Male',
                            inputValue: 'Male',
                            margin: '0 10 0 0'
                        }, {
                            xtype: 'radiofield',
                            name: 'gender',
                            boxLabel: 'Female',
                            inputValue: 'Female'
                        }]
                    }]
                }]
            }, {
                xtype: 'container',
                margin: '10 5 0 0',
                defaults: {
                    anchor: '100%'
                },
                layout: 'anchor',
                items: [{
                    xtype: 'filefield',
                    anchor: '100%',
                    fieldLabel: 'Upload Image',
                    name: 'profilePhoto'
                }, {
                    xtype: 'tagfield',
                    anchor: '100%',
                    fieldLabel: 'Allergies',
                    name: 'allergies',
                    store: 'Allergies'
                }, {
                    xtype: 'fieldset',
                    anchor: '100% -250',
                    title: 'Pre-Existing Conditions',
                    items: [{
                        xtype: 'checkboxgroup',
                        reference: 'preexistingconditions',
                        hideLabel: true,
                        items: [{
                            xtype: 'checkboxfield',
                            fieldLabel: 'Label',
                            boxLabel: 'Box Label'
                        }]
                    }]
                }, {
                    xtype: 'tinymce',
                    height: 175,
                    fieldLabel: 'Notes',
                    labelAlign: 'top',
                    name: 'notes'
                }]
            }],
            tools: [{
                xtype: 'tool',
                type: 'save',
                listeners: {
                    click: 'onSavePatientInfo'
                }
            }],
            listeners: {
                beforerender: 'onFormBeforeRender'
            }
        }, {
            xtype: 'patientprocedures',
            reference: 'visitdetail'
        }, {
            xtype: 'patientchartgraphsgraphs',
            reference: 'graphs'
        }, {
            xtype: 'patientmedia',
            reference: 'media'
        }]
    }, {
        xtype: 'patientchartanatomy',
        collapsible: true,
        title: 'Grey\'s Anatomy',
        region: 'east',
        split: true,
        splitterResize: false
    }]

});