/*
 * File: app/view/research/clinicaltrials/ClinicalTrialsViewController.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PatientChart.view.research.clinicaltrials.ClinicalTrialsViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.clinicaltrialsviewcontroller',

    requires: [
        'Ext.ux.IFrame'
    ],

    onSearchFieldChange: function() {
        this.getStore('ClinicalTrials').removeAll();
        this.getStore('ClinicalTrials').clearFilter(true);
       
        var recr = this.lookupReference('recrfield').getValue() || "";
       
        this.getStore('ClinicalTrials').filter([{
            property: 'term',
            value: this.lookupReference('termfield').getValue()
        }, {
            property: 'recr',
            value: recr
        }]);
    },

    onWindowBeforeShow: function(component, eOpts) {
        this.getStore('ClinicalTrials').load();
    },

    onClinicalTrialsLoad: function(store) {
       this.getView().setTitle("Clinical Trials - " + Ext.util.Format.number(store.getTotalCount(),'0,000') + " found");
    },

    onClearFilters: function(b) {
        this.lookupReference('recrfield').setValue(null);
        this.lookupReference('termfield').setValue('');
        this.onSearchFieldChange();
    },

    onSearch: function(b) {
        this.onSearchFieldChange();
    },
    
    displayTrialWebSite: function(b,e) {
        
        var perspective = b.up('researchPerspective');
        var selectedTrial = this.getViewModel().get('selectedTrial');
        
        perspective.add({
            xtype: 'window',
            width: 800,
            height: 600,
            title: selectedTrial.get('title'),
            maximizable: true,
            constrain: true,
            layout: 'fit',
            items: [
                {
                    xtype: 'uxiframe',
                    src: selectedTrial.get('url')
                }
            ]
        }).show();

    }

});