/*
 * File: app/view/research/clinicaltrials/ClinicalTrialsViewModel.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PatientChart.view.research.clinicaltrials.ClinicalTrialsViewModel', {
    extend: 'Ext.app.ViewModel',
    alias: 'viewmodel.clinicaltrialsviewmodel',

    requires: [
        'Ext.data.BufferedStore',
        'PatientChart.model.ClinicalTrial'
    ],

    data: {
        selectedTrial: null,
        filterTerm: '',
        recr: null
    },

    stores: {
        ClinicalTrials: {
            type: 'buffered',
            model: 'PatientChart.model.ClinicalTrial',
            remoteFilter: true,
            remoteSort: true,
            listeners: {
                load: 'onClinicalTrialsLoad'
            }
        }
    }

});