/*
 * File: app/view/research/Research.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PatientChart.view.research.Research', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.researchPerspective',

    requires: [
        'PatientChart.view.research.ResearchViewModel'
    ],

    viewModel: {
        type: 'researchresearch'
    },
    cls: 'appBackground',
    height: 250,
    width: 400

});