/*
 * File: app/view/navigation/NavigationViewController.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PatientChart.view.navigation.NavigationViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.navigationviewcontroller',

    onAllergiesClick: function(item, e, eOpts) {
        this.redirectTo('admin/allergies');
    },

    onPreExistingConditionsClick: function(item, e, eOpts) {
        this.redirectTo('admin/preexistingconditions');
    },

    onBillingCodesClick: function(item, e, eOpts) {
        this.redirectTo('admin/billingcodes');
    },

    onAdministrationClick: function(button, e, eOpts) {
        this.redirectTo('admin');
    },

    onAdminArrowClick: function(splitbutton, e, eOpts) {
        this.redirectTo('admin');
    },

    onPatientSearch: function(item, e, eOpts) {
        this.redirectTo('patient/search');
    },

    onPatientPerspectiveClick: function(button, e, eOpts) {
        this.redirectTo('patient/search');
    },

    onClinicalTrialsClick: function(item, e, eOpts) {
        this.redirectTo('research/clinicaltrials');
    },

    onMenuitemClick: function(item, e, eOpts) {
        this.redirectTo('research/hospitalstats');
    },

    onResearchArrowClick: function(splitbutton, e, eOpts) {
        this.redirectTo('research');
    },

    onResearchClick: function(button, e, eOpts) {
        this.redirectTo('research');
    }

});
