/*
 * File: app/view/navigation/Navigation.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PatientChart.view.navigation.Navigation', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.navigation',

    requires: [
        'PatientChart.view.navigation.NavigationViewModel',
        'PatientChart.view.navigation.NavigationViewController',
        'Ext.button.Split',
        'Ext.menu.Menu',
        'Ext.menu.Item',
        'PatientChart.view.about.About'
    ],

    controller: 'navigationviewcontroller',
    viewModel: {
        type: 'navigationviewmodel'
    },
    width: 150,
    defaults: {
        height: 45,
        margin: '0 0 10 0',
        toggleGroup: 'perspectives',
        allowDepress: false
    },
    bodyPadding: 5,
    header: false,
    title: 'Navigate',

    layout: {
        type: 'vbox',
        align: 'stretch'
    },

    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'bottom',
            height: 30,
            pack: 'center',
            
            style: {
                'border-top-width' : '1px !important'
            },
            items : [
                {
                    xtype: 'tbtext',
                    flex: 1,
                    style: {
                        'text-align' : 'center'
                    },
                    bind: {
                        text: '{username}'
                    }
                }
            ]
        }
    ],

    items: [
        {
            xtype: 'component',
            width: 150,
            height: 133,
            cls: 'drextlogo'
        },
        {
            xtype: 'splitbutton',
            itemId: 'btnAdminPerspective',
            iconCls: 'btnAdminIcon',
            text: 'Administer',
            menu: {
                xtype: 'menu',
                width: 182,
                items: [
                    {
                        xtype: 'menuitem',
                        width: 138,
                        text: 'Allergies',
                        listeners: {
                            click: 'onAllergiesClick'
                        }
                    },
                    {
                        xtype: 'menuitem',
                        text: 'Pre-Existing Conditions',
                        listeners: {
                            click: 'onPreExistingConditionsClick'
                        }
                    },
                    {
                        xtype: 'menuitem',
                        text: 'Billing Codes/Procedures',
                        listeners: {
                            click: 'onBillingCodesClick'
                        }
                    }
                ]
            },
            listeners: {
                click: 'onAdministrationClick',
                arrowclick: 'onAdminArrowClick'
            }
        },
        {
            xtype: 'splitbutton',
            itemId: 'btnPatientchartPerspective',
            iconCls: 'btnPatientsIcon',
            text: 'Patients',
            menu: {
                xtype: 'menu',
                width: 150,
                items: [
                    {
                        xtype: 'menuitem',
                        text: 'Search',
                        listeners: {
                            click: 'onPatientSearch'
                        }
                    },
                    {
                        xtype: 'menuitem',
                        text: 'Add New'
                    }
                ]
            },
            listeners: {
                click: 'onPatientPerspectiveClick'
            }
        },
        {
            xtype: 'splitbutton',
            itemId: 'btnResearchPerspective',
            iconCls: 'btnResearchIcon',
            text: 'Research',
            menu: {
                xtype: 'menu',
                width: 150,
                items: [
                    {
                        xtype: 'menuitem',
                        text: 'Clinical Trials',
                        listeners: {
                            click: 'onClinicalTrialsClick'
                        }
                    },
                    {
                        xtype: 'menuitem',
                        text: 'Hospital Stats',
                        listeners: {
                            click: 'onMenuitemClick'
                        }
                    }
                ]
            },
            listeners: {
                arrowclick: 'onResearchArrowClick',
                click: 'onResearchClick'
            }
        },
        {
            xtype: 'button',
            text: 'About',
            toggleGroup: null,
            iconCls: 'btnAbout',
            handler: function() {
                Ext.widget('about');
            }
        }
    ]

});