/*
 * File: app/store/Allergies.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PatientChart.store.Allergies', {
    extend: 'Ext.data.Store',

    requires: [
        'PatientChart.model.Allergy',
        'Ext.util.Sorter'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'Allergies',
            autoLoad: true,
            model: 'PatientChart.model.Allergy',
            sorters: {
                property: 'text'
            }
        }, cfg)]);
    }
});